### ISSUE TITLE
Migration hanging on "Finished Adding object hash to statements"

### ISSUE THREAD

**Issue by ddubyah** [LearningLocker/v1-to-v2-migrator#10]
Hi all. I'm testing the v1-v2 migration on a backup of our staging db. It just seems to hang:

```bash
2017-11-16T11:48:11.559Z Started Adding object hash to statements
Error: Argument passed in must be a single String of 12 bytes or a string of 24 hex characters
    at new ObjectID (/Users/darren.wallace/wip/workspace/virtual_environments/docker_boxes/learninglocker_boxes/v1-to-v2-migrator/node_modules/bson/lib/bson/objectid.js:50:11)
    at Function.ObjectID (/Users/darren.wallace/wip/workspace/virtual_environments/docker_boxes/learninglocker_boxes/v1-to-v2-migrator/node_modules/bson/lib/bson/objectid.js:31:42)
    at db (/Users/darren.wallace/wip/workspace/virtual_environments/docker_boxes/learninglocker_boxes/v1-to-v2-migrator/src/migrateLocalData.js:16:39)
    at mongodb.MongoClient.connect.then (/Users/darren.wallace/wip/workspace/virtual_environments/docker_boxes/learninglocker_boxes/v1-to-v2-migrator/src/localConnect.js:13:20)
    at process._tickDomainCallback (internal/process/next_tick.js:129:7)
2017-11-16T11:48:11.586Z Finished updating client 55c734b27446ff15098b4571
2017-11-16T11:48:11.590Z Finished updating client 5a0343bc7446ff5c528b4567
2017-11-16T11:48:11.592Z Finished updating client 55c734b27446ff15098b4570
2017-11-16T11:48:11.593Z Finished updating client 55c734b27446ff15098b456f
2017-11-16T11:48:11.886Z Finished migrating statements client for 5a0343bc7446ff5c528b4567
2017-11-16T11:48:11.886Z Finished migrating statements client for 55c734b27446ff15098b456f
2017-11-16T11:48:11.887Z Finished migrating statements client for 55c734b27446ff15098b4570
2017-11-16T11:48:13.157Z Starting new batch of 10000
2017-11-16T11:48:20.991Z Finished migrating statements client for 55c734b27446ff15098b4571
2017-11-16T11:48:23.106Z Starting new batch of 10000
2017-11-16T11:48:31.897Z Starting new batch of 10000
2017-11-16T11:48:38.652Z Starting new batch of 10000
2017-11-16T11:48:45.491Z Starting new batch of 10000
2017-11-16T11:48:54.633Z Starting new batch of 10000
2017-11-16T11:49:01.836Z Finished migrating statement hashes
2017-11-16T11:49:01.838Z Finished Adding object hash to statements
```

You can see the error message at the top "`Error: Argument passed in must be a single String of 12 bytes or a string of 24 hex characters`", but things do seem to progress from there. Any ideas?

**Comment by ht2** [comment]
Your `target.organisation` in your config is not a valid Mongo ObjectID. Please refer to the docs about [Target ](https://github.com/LearningLocker/v1-to-v2-migrator#target)for details
