### ISSUE TITLE
On persona processing step, error thrown

### ISSUE THREAD

**Issue by maharlikans** [LearningLocker/v1-to-v2-migrator#11]
Hi guys, 

I hope you are well. I wanted to let you know about an error I've been having while trying to perform the final step of the migration, on the persona processing step, executed by this command: 

`node cli/dist/server batchJobs -j personas -b 1000`

Here is the error below, you can see I changed the batch size to 100 because the memory on our server wasn't quite as high to handle batch sizes of 1000
> 2017-12-28 19:15:40:524 - info: Finished batch of 100 (4800)
2017-12-28 19:15:40:527 - error:  Error
    at model.wrappedPointCut [as save] (/usr/local/learninglocker/releases/ll-20171030-b69600374d54c0354ba79ca259f9e55e3d6fab54/webapp/node_modules/mongoose/lib/services/model/applyHooks.js:123:29)
    at /usr/local/learninglocker/releases/ll-20171030-b69600374d54c0354ba79ca259f9e55e3d6fab54/webapp/cli/dist/server/webpack:/tmp/learninglocker/webapp/lib/classes/PersonaFinder.js:1048:27
    at /usr/local/learninglocker/releases/ll-20171030-b69600374d54c0354ba79ca259f9e55e3d6fab54/webapp/node_modules/async/dist/async.js:421:16
    at iteratorCallback (/usr/local/learninglocker/releases/ll-20171030-b69600374d54c0354ba79ca259f9e55e3d6fab54/webapp/node_modules/async/dist/async.js:998:13)
    at /usr/local/learninglocker/releases/ll-20171030-b69600374d54c0354ba79ca259f9e55e3d6fab54/webapp/node_modules/async/dist/async.js:906:16
    at /usr/local/learninglocker/releases/ll-20171030-b69600374d54c0354ba79ca259f9e55e3d6fab54/webapp/cli/dist/server/webpack:/tmp/learninglocker/webapp/lib/classes/PersonaFinder.js:1033:19
    at Query.<anonymous> (/usr/local/learninglocker/releases/ll-20171030-b69600374d54c0354ba79ca259f9e55e3d6fab54/webapp/node_modules/mongoose/lib/model.js:3835:16)
    at /usr/local/learninglocker/releases/ll-20171030-b69600374d54c0354ba79ca259f9e55e3d6fab54/webapp/node_modules/kareem/index.js:273:21
    at /usr/local/learninglocker/releases/ll-20171030-b69600374d54c0354ba79ca259f9e55e3d6fab54/webapp/node_modules/kareem/index.js:131:16
    at _combinedTickCallback (internal/process/next_tick.js:73:7)
    at process._tickDomainCallback (internal/process/next_tick.js:128:9)
2017-12-28 19:15:40:533 - error:  Error
    at model.wrappedPointCut [as save] (/usr/local/learninglocker/releases/ll-20171030-b69600374d54c0354ba79ca259f9e55e3d6fab54/webapp/node_modules/mongoose/lib/services/model/applyHooks.js:123:29)
    at /usr/local/learninglocker/releases/ll-20171030-b69600374d54c0354ba79ca259f9e55e3d6fab54/webapp/cli/dist/server/webpack:/tmp/learninglocker/webapp/lib/classes/PersonaFinder.js:1048:27
    at /usr/local/learninglocker/releases/ll-20171030-b69600374d54c0354ba79ca259f9e55e3d6fab54/webapp/node_modules/async/dist/async.js:421:16
    at iteratorCallback (/usr/local/learninglocker/releases/ll-20171030-b69600374d54c0354ba79ca259f9e55e3d6fab54/webapp/node_modules/async/dist/async.js:998:13)
    at /usr/local/learninglocker/releases/ll-20171030-b69600374d54c0354ba79ca259f9e55e3d6fab54/webapp/node_modules/async/dist/async.js:906:16
    at /usr/local/learninglocker/releases/ll-20171030-b69600374d54c0354ba79ca259f9e55e3d6fab54/webapp/cli/dist/server/webpack:/tmp/learninglocker/webapp/lib/classes/PersonaFinder.js:1033:19
    at Query.<anonymous> (/usr/local/learninglocker/releases/ll-20171030-b69600374d54c0354ba79ca259f9e55e3d6fab54/webapp/node_modules/mongoose/lib/model.js:3835:16)
    at /usr/local/learninglocker/releases/ll-20171030-b69600374d54c0354ba79ca259f9e55e3d6fab54/webapp/node_modules/kareem/index.js:273:21
    at /usr/local/learninglocker/releases/ll-20171030-b69600374d54c0354ba79ca259f9e55e3d6fab54/webapp/node_modules/kareem/index.js:131:16
    at _combinedTickCallback (internal/process/next_tick.js:73:7)
    at process._tickDomainCallback (internal/process/next_tick.js:128:9)

**Comment by ryansmith94** [comment]
For anyone visiting this issue, this issue is not related to this repository, it's actually an issue in https://github.com/LearningLocker/learninglocker.

Hi @maharlikans, which migration are you referring to when you say.

> perform the final step of the migration, on the persona processing step
