### ISSUE TITLE
When a file for document migration doesn't exist, the process fails - it should ignore the record and process the rest

### ISSUE THREAD

**Issue by mparnelldmp** [LearningLocker/v1-to-v2-migrator#24]
```2020-06-01T21:20:20.107Z Started Getting state documents from v1
2020-06-01T21:20:20.111Z Started Getting activityProfile documents from v1
2020-06-01T21:20:20.165Z Started Getting agentProfile documents from v1
2020-06-01T21:20:20.685Z Starting new statements batch of 1000
2020-06-01T21:20:20.942Z Reading file from /mnt/lmsfiles/tmpstor/5956ad4523a9eb2e0cbc3abc/documents/1562612719_677.bin
2020-06-01T21:20:21.181Z Finished migrating documents
2020-06-01T21:20:21.182Z Finished migrating documents
events.js:174
      throw er; // Unhandled 'error' event
      ^

Error: ENOENT: no such file or directory, open '/mnt/lmsfiles/tmpstor/5956ad4523a9eb2e0cbc3abc/documents/1562612719_677.bin'
Emitted 'error' event at:
    at /home/nodeuser/v1-to-v2-migrator/node_modules/fs-extra/node_modules/graceful-fs/graceful-fs.js:190:14
    at /home/nodeuser/v1-to-v2-migrator/node_modules/fs-extra/node_modules/graceful-fs/graceful-fs.js:241:16
    at FSReqWrap.args [as oncomplete] (fs.js:140:20)```

**Comment by mparnelldmp** [comment]
...turns out that the script has trouble if any .bin files are missing...and for whatever reason I did have.

I nuked those records and will try again.
